version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: healthygym
      MYSQL_USER: user
      MYSQL_PASSWORD: '0000'
      MYSQL_ROOT_PASSWORD: '0000'
      LANG: C.UTF-8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - springboot-mysql-net

  backend:
    container_name: backend
    build: .
    restart: always
    image: suaahn/gym-backend:0.1
    volumes:
      - /home/ubuntu/projects/config:/config
    environment:
      CONFIG_LOCATION: /home/ubuntu/projects/config/application.properties
      MYSQL_HOST: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthygym?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: '0000'
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge